### ISSUE TITLE
what is the error here

### ISSUE THREAD

**Issue by BalesabuGodugu** [learn-co-curriculum/js-principles-scope-lab#4]
var customerName="bob";
function upperCaseCustomerName(){
return customerName.toUpperCase();
}

**Comment by itzsaga** [comment]
Hey @BalesabuGodugu,

These issues aren't for questions but for issues with the lab. I hope you've moved forward by utilizing Ask A Question or another resource available to you.

If you look closely at the tests you will see that the tests are wanting us to change the `customerName` variable and not just return a string:

![image](https://user-images.githubusercontent.com/11750061/37068530-d1e80e76-2174-11e8-9df6-0eb60edf7796.png)

**Comment by maxwellbenton** [comment]
Hi @BalesabuGodugu,

If you declare a variable and assign to a string, calling `.toUpperCase()` on that variable _will_ return the upper cased string as output, but _will not_ redefine the variable. Your function does return the uppercased string, but that string isn't be assigned to anything, and the original variable continues to equal 'bob'.

Since the test is to modify the variable, you will need to assign it the upper cased version of itself.
